[project]
name = "guionardo"
version = "0.1.0"
description = "Guionardo's GitHub Page Builder"
authors = ["Guionardo (Desktop Linux) <guionardo@gmail.com>"]

readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "httpx>=0.28.1",
    "pygal>=3.1.0",
]
